spring.config.import=file:backend/.env[.properties]

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Biar jelas mau kemana dah ini connectnya
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Untuk Membuat / perbatui table di database secara otomatis
spring.jpa.hibernate.ddl-auto=update

# Untuk Menampilakan SQL Query di console
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.application.name=demo
